CREATE MANAGED ACCOUNT CONSUMER_READER_ACCOUNT  
ADMIN_NAME  = ADMIN_JACK
ADMIN_PASSWORD = 'Jackson@1234567890'
TYPE = READER;

SHOW MANAGED ACCOUNTS;

DROP MANAGED ACCOUNT CONSUMER_READER_ACCOUNT; 


ALTER SHARE SHARE_HRMS_HR ADD ACCOUNT = VRB92182;

SHOW SHARES ;

SHOW DATABASES;
