CREATE OR REPLACE CATALOG INTEGRATION CAT_INT_GLUE
CATALOG_SOURCE = GLUE
CATALOG_NAMESPACE = 'hrms'
TABLE_FORMAT = ICEBERG
GLUE_AWS_ROLE_ARN = 'arn:aws:iam::904233092605:role/iceberg_unmanaged_si'
GLUE_CATALOG_ID = '904233092605'
GLUE_REGION = 'us-west-2'
ENABLED = TRUE;

CREATE OR REPLACE ICEBERG TABLE HR.AWS_ATHENA_EMPLOYEES_ICEBERG CATALOG = CAT_INT_GLUE EXTERNAL_TABLE_NAME = 'employees_iceberg';
