-----------------------------
-- External Table LAB 3 
-----------------------------
--   Context
USE DATABASE HRMS; 
USE SCHEMA HR; 

CREATE OR REPLACE STAGE HRMS.HR.AWS_ET_PARTITIONED_CSV_STAGE 
STORAGE_INTEGRATION = AWS_S3_INT 
URL = 's3://learn2cloud-snowflake/external_table/et_partition/' 
FILE_FORMAT = CSV_ET_FILEFORMAT 
LIST @AWS_ET_PARTITIONED_CSV_STAGE; 
CREATE OR REPLACE EXTERNAL TABLE EXT_EMPLOYEES_PARTITIONED 
( 
EMPLOYEE_ID    VARCHAR   AS (VALUE:c1::VARCHAR), 
FIRST_NAME     VARCHAR   AS (VALUE:c2::VARCHAR), 
LAST_NAME      VARCHAR   AS (VALUE:c3::VARCHAR), 
EMAIL          
VARCHAR   AS (VALUE:c4::VARCHAR), 
PHONE_NUMBER   VARCHAR   AS (VALUE:c5::VARCHAR), 
HIRE_DATE      VARCHAR   AS (VALUE:c6::VARCHAR), 
JOB_ID         
VARCHAR   AS (VALUE:c7::VARCHAR), 
SALARY         
VARCHAR   AS (VALUE:c8::VARCHAR), 
COMMISSION_PCT VARCHAR   AS (VALUE:c9::VARCHAR), 
MANAGER_ID     VARCHAR   AS (VALUE:c10::VARCHAR), --DEPARTMENT_ID  VARCHAR   AS (VALUE:c11::VARCHAR) 
DEPARTMENT_ID  varchar AS  split_part(metadata$filename, '/', 3) 
) 
LOCATION=@AWS_ET_PARTITIONED_CSV_STAGE 
PATTERN='.*employees.*[.]csv' 
FILE_FORMAT = CSV_ET_FILEFORMAT; 
SELECT * FROM EXT_EMPLOYEES_PARTITIONED; 
SELECT  metadata$filename FROM EXT_EMPLOYEES_PARTITIONED; 
SELECT metadata$filename,split_part(metadata$filename, '/', 3) FROM 
EXT_EMPLOYEES_PARTITIONED; 
SELECT * FROM EXT_EMPLOYEES_PARTITIONED 
-- WHERE DEPARTMENT_ID=20 