--  Context
USE DATABASE HRMS; 
USE SCHEMA HR; 
-------------------------
-- Create external table
-------------------------
CREATE OR REPLACE EXTERNAL TABLE EXT_EMPLOYEES_REFRESH 
( 
EMPLOYEE_ID    VARCHAR   AS (VALUE:c1::VARCHAR), 
FIRST_NAME     VARCHAR   AS (VALUE:c2::VARCHAR), 
LAST_NAME      VARCHAR   AS (VALUE:c3::VARCHAR), 
EMAIL          
VARCHAR   AS (VALUE:c4::VARCHAR), 
PHONE_NUMBER   VARCHAR   AS (VALUE:c5::VARCHAR), 
HIRE_DATE      VARCHAR   AS (VALUE:c6::VARCHAR), 
JOB_ID         
VARCHAR   AS (VALUE:c7::VARCHAR), 
SALARY         
VARCHAR   AS (VALUE:c8::VARCHAR), 
COMMISSION_PCT VARCHAR   AS (VALUE:c9::VARCHAR), 
MANAGER_ID     VARCHAR   AS (VALUE:c10::VARCHAR), 
DEPARTMENT_ID  VARCHAR   AS (VALUE:c11::VARCHAR) 
) 
LOCATION=@AWS_ET_CSV_STAGE 
AUTO_REFRESH= TRUE 
PATTERN='.*employees.*[.]csv' 
FILE_FORMAT = CSV_ET_FILEFORMAT; 


ALTER EXTERNAL TABLE EXT_EMPLOYEES_REFRESH SET AUTO_REFRESH=FALSE; 
SELECT COUNT(*) FROM EXT_EMPLOYEES_REFRESH; --9  --55 --54 
SELECT * FROM EXT_EMPLOYEES_REFRESH; 
SHOW EXTERNAL TABLES LIKE 'EXT_EMPLOYEES_REFRESH'; 
SELECT  DISTINCT  METADATA$FILENAME FROM EXT_EMPLOYEES_REFRESH; 
ALTER EXTERNAL TABLE EXT_EMPLOYEES_REFRESH REFRESH; 
SELECT COUNT(*) FROM EXT_EMPLOYEES_REFRESH; -- 
SHOW EXTERNAL TABLES LIKE 'EXT_EMPLOYEES_REFRESH'; 
SELECT SYSTEM$EXTERNAL_TABLE_PIPE_STATUS('EXT_EMPLOYEES_REFRESH'); 
CREATE OR REPLACE EXTERNAL TABLE EXT_EMPLOYEES_REFRESH 
( 
EMPLOYEE_ID    VARCHAR   AS (VALUE:c1::VARCHAR), 
FIRST_NAME     VARCHAR   AS (VALUE:c2::VARCHAR), 
LAST_NAME      VARCHAR   AS (VALUE:c3::VARCHAR), 
EMAIL          
VARCHAR   AS (VALUE:c4::VARCHAR), 
PHONE_NUMBER   VARCHAR   AS (VALUE:c5::VARCHAR), 
HIRE_DATE      VARCHAR   AS (VALUE:c6::VARCHAR), 
JOB_ID         
VARCHAR   AS (VALUE:c7::VARCHAR), 
SALARY         
VARCHAR   AS (VALUE:c8::VARCHAR), 
COMMISSION_PCT VARCHAR   AS (VALUE:c9::VARCHAR), 
MANAGER_ID     VARCHAR   AS (VALUE:c10::VARCHAR), 
DEPARTMENT_ID  VARCHAR   AS (VALUE:c11::VARCHAR) 
) 
LOCATION=@AWS_STAGE 
AUTO_REFRESH= TRUE 
PATTERN='.*employees.*[.]csv' 
FILE_FORMAT = CSV_ET_FILEFORMAT;