--  Context
USE DATABASE HRMS; 
USE SCHEMA HR; 
-------------------------
-- Create external table
-------------------------
CREATE OR REPLACE EXTERNAL TABLE EXT_EMPLOYEES_REFRESH 
( 
EMPLOYEE_ID    VARCHAR   AS (VALUE:c1::VARCHAR), 
FIRST_NAME     VARCHAR   AS (VALUE:c2::VARCHAR), 
LAST_NAME      VARCHAR   AS (VALUE:c3::VARCHAR), 
EMAIL          
VARCHAR   AS (VALUE:c4::VARCHAR), 
PHONE_NUMBER   VARCHAR   AS (VALUE:c5::VARCHAR), 
HIRE_DATE      VARCHAR   AS (VALUE:c6::VARCHAR), 
JOB_ID         
VARCHAR   AS (VALUE:c7::VARCHAR), 
SALARY         
VARCHAR   AS (VALUE:c8::VARCHAR), 
COMMISSION_PCT VARCHAR   AS (VALUE:c9::VARCHAR), 
MANAGER_ID     VARCHAR   AS (VALUE:c10::VARCHAR), 
DEPARTMENT_ID  VARCHAR   AS (VALUE:c11::VARCHAR) 
) 
LOCATION=@AWS_ET_CSV_STAGE 
AUTO_REFRESH= TRUE 
PATTERN='.*employees.*[.]csv' 
FILE_FORMAT = CSV_ET_FILEFORMAT; 

DESC EXTERNAL TABLE EXT_EMPLOYEES_REFRESH; -- shows a row for the "value" variant and a row per table column

ALTER EXTERNAL TABLE EXT_EMPLOYEES_REFRESH SET AUTO_REFRESH=TRUE;  -- triggers a metadata true-up to s3
SELECT COUNT(*) FROM EXT_EMPLOYEES_REFRESH; --60   
SELECT * FROM EXT_EMPLOYEES_REFRESH; 
SHOW EXTERNAL TABLES LIKE 'EXT_EMPLOYEES_REFRESH';  -- presence of NOTIFICATION_CHANNEL indicates AUTO_REFRESH=TRUE
SELECT  DISTINCT  METADATA$FILENAME FROM EXT_EMPLOYEES_REFRESH; -- Returns files that currently exist in S3 and are discoverable.

ALTER EXTERNAL TABLE EXT_EMPLOYEES_REFRESH REFRESH; 

-- debug below
LIST @AWS_ET_CSV_STAGE;  -- instantly updated (does not need a refresh of metadata)
-- These next queries require a metadata refresh
SELECT *  -- Returns the full historical metadata Snowflake has recorded for every file ever discovered in the external table’s location, ordered from most recently modified to oldest. Some of this metadata may be stale.
FROM TABLE(
  INFORMATION_SCHEMA.EXTERNAL_TABLE_FILES(
    TABLE_NAME => 'EXT_EMPLOYEES_REFRESH'
  )
)
ORDER BY LAST_MODIFIED DESC;
-- DESC STAGE AWS_ET_CSV_STAGE;
SELECT * FROM TABLE(INFORMATION_SCHEMA.EXTERNAL_TABLE_FILES('EXT_EMPLOYEES_REFRESH'));
-- debug above

SELECT COUNT(*) FROM EXT_EMPLOYEES_REFRESH; -- 105
SHOW EXTERNAL TABLES LIKE 'EXT_EMPLOYEES_REFRESH'; 
SELECT SYSTEM$EXTERNAL_TABLE_PIPE_STATUS('EXT_EMPLOYEES_REFRESH');  -- Tells if the listner is ACTIVE in polling for SQS messages and if there are messages to be consumed
CREATE OR REPLACE EXTERNAL TABLE EXT_EMPLOYEES_REFRESH 
( 
EMPLOYEE_ID    VARCHAR   AS (VALUE:c1::VARCHAR), 
FIRST_NAME     VARCHAR   AS (VALUE:c2::VARCHAR), 
LAST_NAME      VARCHAR   AS (VALUE:c3::VARCHAR), 
EMAIL          
VARCHAR   AS (VALUE:c4::VARCHAR), 
PHONE_NUMBER   VARCHAR   AS (VALUE:c5::VARCHAR), 
HIRE_DATE      VARCHAR   AS (VALUE:c6::VARCHAR), 
JOB_ID         
VARCHAR   AS (VALUE:c7::VARCHAR), 
SALARY         
VARCHAR   AS (VALUE:c8::VARCHAR), 
COMMISSION_PCT VARCHAR   AS (VALUE:c9::VARCHAR), 
MANAGER_ID     VARCHAR   AS (VALUE:c10::VARCHAR), 
DEPARTMENT_ID  VARCHAR   AS (VALUE:c11::VARCHAR) 
) 
LOCATION=@AWS_STAGE 
AUTO_REFRESH= TRUE 
PATTERN='.*employees.*[.]csv' 
FILE_FORMAT = CSV_ET_FILEFORMAT;