USE DATABASE HRMS;

USE SCHEMA ZEROCOPY;

CREATE OR REPLACE TABLE EMPLOYEES_SNOWPIPE
(
    EMPLOYEE_ID         NUMBER ,
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(25),
    EMAIL               VARCHAR(25),
    PHONE_NUMBER        VARCHAR(20),
    HIRE_DATE           DATE,
    JOB_ID              VARCHAR(10),
    SALARY              NUMBER(8, 2),
    COMMISSION_PCT      NUMBER(2, 2),
    MANAGER_ID          NUMBER(6),
    DEPARTMENT_ID       NUMBER(4)
);

CREATE OR REPLACE FILE FORMAT HRMS.ZEROCOPY.CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0;

CREATE OR REPLACE STAGE HRMS.ZEROCOPY.AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = UDEMY_MC_A1_SI
URL = 's3://vdw-dev-ingest/loadingdatalabs/csv/'
-- URL = 's3://learn2cloud-snowflake/snowpipe/csv/'
FILE_FORMAT = CSV_PIPE_FILEFORMAT;
desc integration UDEMY_MC_A1_SI;
-- s3://vdw-dev-ingest/loadingdatalabs/,s3://vdw-dev-ingest/loadingdatalabs/labcsv/,s3://vdw-dev-ingest/loadingdatalabs/
--     json/,s3://vdw-dev-ingest/loadingdatalabs/unloadingdata/csv/

CREATE OR REPLACE PIPE PIPE_EMPLOYEES 
(
  AUTO_INGEST = TRUE,
  WAREHOUSE = 'COMPUTE_WH'
)
AS
COPY INTO EMPLOYEES_SNOWPIPE 
FROM @AWS_PIPE_CSV_STAGE;

CREATE OR REPLACE PIPE PIPE_EMPLOYEES_REPLICA CLONE PIPE_EMPLOYEES; -- Serverless pipes cannot be cloned
CREATE OR REPLACE SCHEMA ZEROCLONE;

CREATE OR REPLACE TABLE EMPLOYEES_SNOWPIPE
(
    EMPLOYEE_ID         NUMBER ,
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(25),
    EMAIL               VARCHAR(25),
    PHONE_NUMBER        VARCHAR(20),
    HIRE_DATE           DATE,
    JOB_ID              VARCHAR(10),
    SALARY              NUMBER(8, 2),
    COMMISSION_PCT      NUMBER(2, 2),
    MANAGER_ID          NUMBER(6),
    DEPARTMENT_ID       NUMBER(4)
);


CREATE OR REPLACE FILE FORMAT CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0 ;


CREATE OR REPLACE STAGE AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = UDEMY_MC_A1_SI
URL ='s3://vdw-dev-ingest/loadingdatalabs/csv/'
FILE_FORMAT = CSV_PIPE_FILEFORMAT;



CREATE OR REPLACE PIPE PIPE_EMPLOYEES
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE FROM @AWS_PIPE_CSV_STAGE;


CREATE OR REPLACE VIEW VIEW_EMPLOYEES
AS
SELECT * FROM EMPLOYEES_SNOWPIPE;


CREATE OR REPLACE SCHEMA ZEROCLONE_REPLICA CLONE ZEROCLONE;


SHOW PIPES;

SHOW VIEWS;

SHOW STAGES;

SHOW FILE FORMATS;

--DATABASE CLONING

CREATE OR REPLACE DATABASE ZEROCOPYDB;


CREATE OR REPLACE SCHEMA ZEROCOPY1;


CREATE OR REPLACE SCHEMA ZEROCOPY2;

SHOW SCHEMAS;


CREATE OR REPLACE DATABASE ZEROCOPYDB_REPLICA CLONE ZEROCOPYDB ;

SHOW DATABASES LIKE 'ZEROCOPYDB%';


SHOW SCHEMAS;