-- Set context
use database hrms;
use database hr;

--------------------------------
-- CREATE THE EMPLOYEE TABLE
--------------------------------
CREATE OR REPLACE TABLE HRMS.HR.EMPLOYEE
(
    EMPLOYEE_ID     NUMBER,
    FIRST_NAME      VARCHAR,
    LAST_NAME       VARCHAR,
    EMAIL           VARCHAR,
    PHONE_NUMBER    VARCHAR,
    HIRE_DATE       VARCHAR,
    JOB_ID          VARCHAR,
    SALARY          VARCHAR,
    COMMISSION_PCT  NUMBER(38,2),
    MANAGER_ID      VARCHAR,
    DEPARTMENT_ID   VARCHAR
);


--------------------------------
-- LOAD THE EMPLOYEE DATA FROM EXTERNAL TABLE (SEE MC_LOADING_SEMI_STRUCTURED_DATA_LAB.SQL IN THE SEMISTRUCTUREDDATA FOLDER)
--------------------------------
INSERT INTO HRMS.HR.EMPLOYEE 
(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
)
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
FROM HRMS.HR.EXT_EMPLOYEES_FORMAT_DATE_EMPLOYEE_ID_COMMISSION_PCT;
