CREATE USER myusername PASSWORD = 'mypassword' 
MUST_CHANGE_PASSWORD = FALSE 
DEFAULT_ROLE = ACCOUNTADMIN 
DEFAULT_WAREHOUSE = NULL 
DEFAULT_NAMESPACE = NULL; 
GRANT ROLE ACCOUNTADMIN TO USER myusername;
